language: python

python:
  - "3.4"

services:
  - "mysql"

install: 
  - "pip install pep8"
  - "pip install -r req.txt"

before_script:
  - "mysql -e 'create database travis_ci_db;'"
  - "pep8 --exclude=migrations,templates,settings.py ."

script:
  - "python manage.py test"
